### ISSUE TITLE
Version 1.5.0 is not the latest version available for this package...

### ISSUE THREAD

**Issue by spentacular** [simurai/one-dark-vivid-syntax#4]
I'm not sure if this has anything to do with [Atom #13294](https://github.com/atom/atom/issues/13294), but I had some troubles re-installing One Dark Vivid. The package search also looks like this when searching:

![screen shot 2016-11-28 at 7 36 08 am](https://cloud.githubusercontent.com/assets/1043478/20670395/52cef58a-b53e-11e6-93a8-05a434f16beb.png)

I had some syntax highlighting errors as well, which I think the root comes from having the `sync-settings` package potentially referencing the original one dark syntax. 

Every time I try to install vivid, it just appears to stall out. I don't see any errors in the Developer Console either, just the Install button looking like:

![install-button](https://cloud.githubusercontent.com/assets/1043478/20670381/42bb10e8-b53e-11e6-8aef-0ce119846eca.png)

When I try to install via `apm`, it only ever adds the one-dark-syntax package back on as a community one, not vivid.

I'm currently running Atom 1.12.5

**Comment by simurai** [comment]
The settings seem accurate.

- one-dark-vivid-syntax `1.5.0` is for Atom `1.12.5`.
- one-dark-vivid-syntax `1.6.0` will be for Atom `>1.13.0` (currently still in Beta).

So in your case, being on Atom `1.12.5` should install one-dark-vivid-syntax `1.5.0`. Not sure why it hangs. You might can try to temporarily disable `sync-settings`, but I don't think it has anything to do which version gets installed or that it somehow checks if it's the latest.

What if you try to install `1.5.0` explicitly: `apm install one-dark-vivid-syntax@1.5.0`. Does that work?

**Comment by spentacular** [comment]
On a completely fresh install, with `~/.atom` deleted, the only thing I've run is `apm install one-dark-vivid-syntax@1.5.0` and it just installs `one-dark-syntax` (not the vivid):

<img width="776" alt="screen shot 2016-11-28 at 8 12 18 pm" src="https://cloud.githubusercontent.com/assets/1043478/20693905/28f6a9d8-b5a7-11e6-8e93-9b0ded14b1f6.png">

This was using todays update to 1.12.6 as well.

**Comment by simurai** [comment]
Ouch.. I think I know what the problem is. Something with the tags got messed up. Notice if you go to https://github.com/simurai/one-dark-vivid-syntax/tree/v1.5.0 it says "One Dark Syntax theme".

I'll try to clean that up, thanks for noticing. 👍

**Comment by simurai** [comment]
@spentacular Ok, tags should be fixed, if you wanna give it another try.

**Comment by spentacular** [comment]
Yep! That worked perfectly. Thanks for the quick fix and awesome theme!
